export const ORACULOS = [
  "El destino no es lo que creemos. – Terminator 2: Judgment Day",
  "La realidad es simplemente una ilusión, aunque muy persistente. The Matrix",
  "No es el año 2019, es el año 1984. Brazil",
  "No puedes cambiar tu naturaleza. Blade Runner 2049",
  "El tiempo es un círculo plano. Predestination",
  "Las cosas que posees terminan poseyéndote. Fight Club (No es 100% sci-fi, pero resuena en la distopía)",
  "No es la respuesta que esperas, pero es la única que recibirás. Ex Machina",
  "La ignorancia es fuerza. 1984",
  "Lo que es real no se puede borrar. Eternal Sunshine of the Spotless Mind",
  "Los sueños son mensajes del profundo. Dune (2021)",
  "El fin no es el fin. Cloud Atlas",
  "No confíes en tus recuerdos. Total Recall",
  "El futuro ya ha sucedido. 12 Monkeys",
  "La verdad está ahí afuera. The X-Files (Serie, pero influyente)",
  "La realidad es aquello que, cuando dejas de creer en ella, no desaparece. A Scanner Darkly",
  "Todo lo que conoces está equivocado. Dark City",
  "Algunas veces, el pasado se niega a quedar atrás. Minority Report",
  "La mente no es un lugar seguro. Inception",
  "El tiempo solo es una prisión si lo crees así. Interstellar",
  "Ellos vigilan, pero nunca intervienen. The Adjustment Bureau",
  "Nada muere jamás realmente. Ghost in the Shell",
  "No todos los prisioneros quieren escapar. The Matrix Resurrections",
  "Elige sabiamente. No tendrás otra oportunidad. The Matrix",
  "Tu mundo es solo una simulación. The Thirteenth Floor",
  "Al final, todo es una cuestión de control. Westworld",
  "Los secretos mejor guardados son los que nadie nota. Gattaca",
  "Lo que empieza debe terminar. The Matrix Revolutions",
  "No eres especial. Eres el resultado de una ecuación. The Matrix Reloaded",
  "El sacrificio es la única constante. Snowpiercer",
  "La evolución no espera a nadie. Lucy",
  "El presente es solo un eco del pasado. Primer",
  "El error humano es la única variable. Blade Runner",
  "Si controlas el código, controlas la realidad. Tron: Legacy",
  "Todo está predestinado, excepto lo inesperado. Edge of Tomorrow",
  "El universo no tiene una sola línea temporal. Coherence",
  "Algunas puertas solo se abren desde dentro. Annihilation",
  "No es lo que ves, es lo que no puedes ver. Under the Skin",
  "El sistema siempre encuentra un reemplazo. Equilibrium",
  "La simulación nunca termina. The Congress",
  "Los límites son solo otra ilusión. Transcendence",
  "El miedo es la clave de todo control. V for Vendetta",
  "No hay revolución sin sacrificio. The Hunger Games",
  "El futuro es una variable, pero no para todos. Tenet",
  "El fin del mundo no es lo que imaginas. Children of Men",
  "Cuando todo lo que conoces cambie, ¿seguirás siendo tú? Moon",
  "Todo lo que hemos construido se desmoronará. Her",
  "Solo los muertos conocen la verdad. The Man in the High Castle",
  "Tu programación no es más fuerte que tu voluntad. I, Robot",
  "Los mitos no desaparecen, solo cambian de forma. The Fountain",
  "El final es solo el principio visto desde otro ángulo. Arrival",
];
