export const ORACULOS = [
  "El destino no es lo que creemos.",
  "La realidad es simplemente una ilusión, aunque muy persistente.",
  "No es el año 2019, es el año 1984.",
  "No puedes cambiar tu naturaleza.",
  "El tiempo es un círculo plano.",
  "Las cosas que posees terminan poseyéndote.",
  "No es la respuesta que esperas, pero es la única que recibirás.",
  "La ignorancia es fuerza. 1984",
  "Lo que es real no se puede borrar.",
  "Los sueños son mensajes del profundo.",
  "El fin no es el fin.",
  "No confíes en tus recuerdos.",
  "El futuro ya ha sucedido.",
  "La verdad está ahí afuera.",
  "La realidad es aquello que, cuando dejas de creer en ella, no desaparece.",
  "Todo lo que conoces está equivocado.",
  "Algunas veces, el pasado se niega a quedar atrás.",
  "La mente no es un lugar seguro.",
  "El tiempo solo es una prisión si lo crees así.",
  "Ellos vigilan, pero nunca intervienen.",
  "Nada muere jamás realmente. Ghost in the Shell",
  "No todos los prisioneros quieren escapar.",
  "Elige sabiamente. No tendrás otra oportunidad.",
  "Tu mundo es solo una simulación.",
  "Al final, todo es una cuestión de control.",
  "Los secretos mejor guardados son los que nadie nota.",
  "Lo que empieza debe terminar.",
  "No eres especial. Eres el resultado de una ecuación.",
  "El sacrificio es la única constante.",
  "La evolución no espera a nadie.",
  "El presente es solo un eco del pasado.",
  "El error humano es la única variable.",
  "Si controlas el código, controlas la realidad.",
  "Todo está predestinado, excepto lo inesperado",
  "El universo no tiene una sola línea temporal.",
  "Algunas puertas solo se abren desde dentro.",
  "No es lo que ves, es lo que no puedes ver.",
  "El sistema siempre encuentra un reemplazo.",
  "La simulación nunca termina. ",
  "Los límites son solo otra ilusión.",
  "El miedo es la clave de todo control.",
  "No hay revolución sin sacrificio.",
  "El futuro es una variable, pero no para todos.",
  "El fin del mundo no es lo que imaginas.",
  "Cuando todo lo que conoces cambie, ¿seguirás siendo tú? ",
  "Todo lo que hemos construido se desmoronará. ",
  "Solo los muertos conocen la verdad. ",
  "Tu programación no es más fuerte que tu voluntad.",
  "Los mitos no desaparecen, solo cambian de forma. ",
  "El final es solo el principio visto desde otro ángulo.",
];
